name: foil_demo
description: A demonstration of wrapping a widget with Foil.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xl: any

dev_dependencies:
  foil:
    path: ../
  very_good_analysis: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
