name: nonsense_foil
description: >
  Wrap a widget with Foil, providing a rainbow shimmer
  that twinkles as the cursor moves as well as
  tons of neat gradient features.
version: 0.9.0+1
repository: https://github.com/ArcaneArts/nonsense-foil
issue_tracker: https://github.com/ArcaneArts/nonsense-foil/issues
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nonsense_spectrum: <=2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


