name: foil
description: >
  Wrap a widget with Foil, providing a rainbow shimmer
  that twinkles as the accelerometer moves.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
